name: kellymelstedcoaching
favicon: null
layout_spectrum: 0.14164150087162852
typography_spectrum: 0.7406728866044432
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edf4fa'
    - '#f4c1a2'
    - '#3b3c58'
    - '#7d92c7'
    - '#f17235'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
